<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Curiosus.Migrations.Utils</PackageId>
        <Title>Utils for Curiosus.Migrations.</Title>
        <Description>Without migrations you need to create a lots of sql scripts that have to be run manually by every developer involved. Migrations solve the problem of evolving a database schema for multiple databases (for example, the developer's local database, the test database and the production database).</Description>
        <Summary>Without migrations you need to create a lots of sql scripts that have to be run manually by every developer involved. Migrations solve the problem of evolving a database schema for multiple databases (for example, the developer's local database, the test database and the production database).</Summary>
        <PackageTags>migrations; migration; migrator; versioning; migration-tool; .net-core; .netstandard; database; curiosus; utils</PackageTags>
        <Language>English</Language>
        
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>

        <Authors>$(CuriosusAuthors), Andrei Vinogradov (@anri-vin)</Authors>
        
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://curiosity-migrations.readthedocs.io/</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/curiosus-dev/Curiosus.Migrations</RepositoryUrl>
        <PackageReleaseNotes>https://github.com/curiosus-dev/Curiosus.Migrations/tree/master/src/Curiosus.Migrations.Utils/CHANGELOG.md</PackageReleaseNotes>

        <LangVersion>11</LangVersion>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;netcoreapp3.1;netstandard2.0;netstandard2.1</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin\Release\netstandard2.0\Curiosus.Migrations.Utils.xml</DocumentationFile>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Curiosus.Migrations\Curiosus.Migrations.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.66" />
    </ItemGroup>

</Project>
